### ISSUE TITLE
New user have to sign twice to connect metamask successfully

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#10]
repo.

1. clear local storage
2. Click on 'Connect' Metamask
3. Signature Request click on 'SIGN'
4. 'Please sign the message for login purpose.' appeared
5. Signature Request click on 'SIGN' again
6. connected successfully

**Comment by cmngan** [comment]
Please check again =]

**Comment by karlischan** [comment]
not yet fixed.
repo.
1.Click on 'Connect' Metamask
2.Signature Request click on 'SIGN'
3.This appeared:
![image](https://user-images.githubusercontent.com/49937934/57055893-18b52480-6cd1-11e9-9778-edb32dfc9d68.png)
4.Click on 'Connect' again
5.Signature Request click on 'SIGN'
6. Connected successfully

OR

1.Click on 'Connect' Metamask
2.Signature Request click on 'SIGN'
3.This appeared:
![image](https://user-images.githubusercontent.com/49937934/57055893-18b52480-6cd1-11e9-9778-edb32dfc9d68.png)
4. Reload the page
5. Connected successfully

**Comment by cmngan** [comment]
now?

**Comment by karlischan** [comment]
FIXED
