### ISSUE TITLE
TRADE - Update icon 

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#102]
Use SmartUp logo for left icon, user profile pic for right icon
![image](https://user-images.githubusercontent.com/19403453/57117575-bb33dd00-6d8f-11e9-97f6-2edf7bf3745a.png)

**Comment by Silcence** [comment]
Fixed

**Comment by hkykit** [comment]
checked
![image](https://user-images.githubusercontent.com/19403453/57221334-6b744080-7031-11e9-964a-4eeb9c79f89b.png)
