### ISSUE TITLE
MP - Redirection from market info

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#105]
Click Market name in slide down bar, redirect to General Page
![image](https://user-images.githubusercontent.com/19403453/57118284-e79e2800-6d94-11e9-8a15-cb1d17568d15.png)

Click #of Subscriber icon in slide down bar, redirect to General Page
Click #of Discussion icon in slide down bar, redirect to Discussion page

**Comment by hkykit** [comment]
related to #60

**Comment by karlischan** [comment]
added
