### ISSUE TITLE
MP - Community member numbers is not working, always show 0

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#106]
![image](https://user-images.githubusercontent.com/49937934/57118862-9a23ba00-6d98-11e9-8fcb-71725255a9a9.png)

![image](https://user-images.githubusercontent.com/49937934/57118879-b0317a80-6d98-11e9-9040-dde09f09491c.png)

**Comment by cmngan** [comment]
@ZhangZhen-SmartUp Please fix userCount
http://39.105.101.248:86/api/market/top?type=richest
![image](https://user-images.githubusercontent.com/20035088/57130648-b8a3a880-6dcc-11e9-9a44-10acdc1f6c84.png)

**Comment by ZhangZhen-SmartUp** [comment]
已经修复好， 但是历史的数据会有问题，可以创建一个新的market，数据会在新的market里是正常的

**Comment by karlischan** [comment]
Problem 1:
With no members and post should show '0'
![image](https://user-images.githubusercontent.com/49937934/57194385-052be700-6f79-11e9-8d78-053fe8f72d2f.png)
![image](https://user-images.githubusercontent.com/49937934/57194394-14129980-6f79-11e9-944a-116d06921be1.png)

Problem 2:
repo.
1. Account A buys the market token and number of community member->1(correct)
no post in discussion
however, the number of post is wrong:
![image](https://user-images.githubusercontent.com/49937934/57194452-b2066400-6f79-11e9-8488-0720d8ee15db.png)
![image](https://user-images.githubusercontent.com/49937934/57194445-a155ee00-6f79-11e9-8f72-6da0db371c48.png)

2. Account B buys the token,  number of community member->2(correct)
no post in discussion
however, the number of post is wrong as showing '2':
![image](https://user-images.githubusercontent.com/49937934/57194510-4e306b00-6f7a-11e9-960a-837030a30683.png)
![image](https://user-images.githubusercontent.com/49937934/57194514-55f00f80-6f7a-11e9-922a-307d1a47770b.png)

**Comment by cmngan** [comment]
@ZhangZhen-SmartUp 
After I Traded, one discussion added. 
Request URL: http://39.105.101.248:86/api/market/one/by/id?marketId=3d7zuix1m9s
![image](https://user-images.githubusercontent.com/20035088/57206380-e6b90080-6ff7-11e9-8d4c-aa5271ea7be4.png)

Discussion:
Request URL: http://39.105.101.248:86/api/post/list?type=market&query=&marketId=3d7zuix1m9s&pageNumb=1&pageSize=10
Response: 0

**Comment by ZhangZhen-SmartUp** [comment]
已修复这个bug，旧的数据没有修改，可以在新创建的市场中看到效果

**Comment by karlischan** [comment]
FIXED
