### ISSUE TITLE
Portfolio - market wallet should not show mkt sold all CT

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#110]
i buy 20000 and then sell out 20000
market still stay in wallet with 0
Expected: mkt with 0 CT should be removed from wallet
![image](https://user-images.githubusercontent.com/19403453/57125953-ed5c3380-6dbd-11e9-8a3d-271cdf0ceaa5.png)

**Comment by cmngan** [comment]
@ZhangZhen-SmartUp

**Comment by ZhangZhen-SmartUp** [comment]
已修复

**Comment by hkykit** [comment]
![image](https://user-images.githubusercontent.com/19403453/57222447-2baf5800-7035-11e9-92bd-284cc1db68dd.png)

**Comment by hkykit** [comment]
fixed
