### ISSUE TITLE
Portfolio - Bookmark should sort by time & redirected to the corresponding market when the market is clicked

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#111]
Now:
added new market, automatically sort by name
click on, no redirection
Expect:
sort by bookmarking time, latest in top. 
redirected to the corresponding market when the market is clicked

![image](https://user-images.githubusercontent.com/49937934/57129434-f43c7380-6dc8-11e9-9d53-40f580725f28.png)

**Comment by ZhangZhen-SmartUp** [comment]
已修复

**Comment by karlischan** [comment]
repo.
1. click on the market in the bookmark
2. redirected to the market
3. go to the main page
4. click on the bookmark button, no response
![image](https://user-images.githubusercontent.com/49937934/57267765-cbabc680-70b3-11e9-8f50-ae4307e0843d.png)
5. click on the 'X', no response too
![image](https://user-images.githubusercontent.com/49937934/57267816-01e94600-70b4-11e9-8207-cc9642484dda.png)

**Comment by karlischan** [comment]
Fixed
