### ISSUE TITLE
MP - BUG when sort in All Tab

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#117]
repo.

1. sort by spot price 細到大
2. load more, load more
3. this bug appeared:
![image](https://user-images.githubusercontent.com/49937934/57135126-f0b1e800-6dda-11e9-94e8-9942352ef6bf.png)
4. go to top sort by spot price again
5. some market cannot be sorted, cannot slide down
![image](https://user-images.githubusercontent.com/49937934/57135313-8e0d1c00-6ddb-11e9-8005-965b791aa10e.png)

![image](https://user-images.githubusercontent.com/49937934/57135427-f3f9a380-6ddb-11e9-9c78-64903c54f008.png)

**Comment by hkykit** [comment]
@karlischan  WHAT IS THIS BUY APPEARED?

**Comment by cmngan** [comment]
@karlischan Cannot reproduce

**Comment by karlischan** [comment]
![image](https://user-images.githubusercontent.com/49937934/57272203-56e18800-70c5-11e9-81ac-93068c24c8be.png)

bug occured in random

**Comment by cmngan** [comment]
@karlischan Please reproduce and tell me when u get the issue again =]

**Comment by karlischan** [comment]
not appear anymore
