### ISSUE TITLE
Discussion - create new post, 'system error' appeared

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#124]
1. Create a new post
2. click on summit
3. 'system error' appeared
![image](https://user-images.githubusercontent.com/49937934/57205249-d4d35f80-6fef-11e9-920c-ee37f8440a4d.png)
4. but the post can still be created when i click
![image](https://user-images.githubusercontent.com/49937934/57205325-8d999e80-6ff0-11e9-8763-245175b792c8.png)

**Comment by ZhangZhen-SmartUp** [comment]
已修复

**Comment by karlischan** [comment]
Fixed
