### ISSUE TITLE
Portfolio - Sell CT, the total SMARTUP invested should not be reduced

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#125]
Before selling CT
![image](https://user-images.githubusercontent.com/49937934/57206180-7cec2700-6ff6-11e9-9127-456c4ffeb662.png)

After sold the CT
![image](https://user-images.githubusercontent.com/49937934/57206213-aad16b80-6ff6-11e9-8087-9f7f1642ac25.png)

![image](https://user-images.githubusercontent.com/49937934/57206221-b7ee5a80-6ff6-11e9-85aa-e35326b94594.png)

**Comment by cmngan** [comment]
@ZhangZhen-SmartUp

**Comment by ZhangZhen-SmartUp** [comment]
kit say keep it

**Comment by hkykit** [comment]
![image](https://user-images.githubusercontent.com/19403453/57270448-e08d5780-70bd-11e9-81f5-1ab8e3d1bf1f.png)

**Comment by hkykit** [comment]
buy ok, sell not ok

**Comment by hkykit** [comment]
works for sell CT too
