### ISSUE TITLE
Detect newest version of portal and redirect user to the newest 

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#128]

**Comment by ZhangZhen-SmartUp** [comment]
接口已近完成

**Comment by hkykit** [comment]
0507 1606
http://ipfs.smartup.global/ipfs/QmRZSbTVnwUAgrBcv3RLdnU87YGPuKmQcC6pCSRUA5JfdY/

0507 1704
http://ipfs.smartup.global/ipfs/QmRNcj3roHy7CC6V5CYAFaPXBeXPDJV51cCj2ciuAw8ock/#/

0507 1930
http://ipfs.smartup.global/ipfs/QmUZ6DLqGU45r2ffG1vkopDKXM9JzVdeWa5yX74XEgtkCZ/#/

**Comment by hkykit** [comment]
only the following one has this function

http://ipfs.smartup.global/ipfs/QmUZ6DLqGU45r2ffG1vkopDKXM9JzVdeWa5yX74XEgtkCZ/#/

and it will be redirected to:
https://ipfs.smartup.global/ipfs/QmVFHq1Cz4jk9AyEr4oqwTqJVBQqfWgNk2nHbYCfi2vsT6/#/
