### ISSUE TITLE
MP spelling mistake in 'Create Market' 

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#130]
![image](https://user-images.githubusercontent.com/49937934/57220155-d2dbc180-702c-11e9-943a-8db1d8e1163a.png)

**Comment by hkykit** [comment]
fixed
![image](https://user-images.githubusercontent.com/19403453/57224900-5a313100-703d-11e9-93c2-b6d1f6b3010d.png)
