### ISSUE TITLE
Trade - Trade immediately after Market Created

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#131]
repo.

1. Create a market successfully,
2. Redirect to the new market
3. Trade immediately
4. error occurred:
![image](https://user-images.githubusercontent.com/49937934/57221249-06204f80-7031-11e9-92b2-f0f7255450a8.png)

Solutions:
Plan A. add a 20 sec cruiser 
Plan B. temporarily disable the trading function

**Comment by hkykit** [comment]
Fixed related to #131
