### ISSUE TITLE
Launch prep - hide unused info

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#137]
- [x] hide Honours
![image](https://user-images.githubusercontent.com/19403453/57286360-b0f34500-70e7-11e9-96c1-366c33504ba1.png)

- [x] hide Dispute
![image](https://user-images.githubusercontent.com/19403453/57286372-b5b7f900-70e7-11e9-9f5a-cfcbca996cff.png)

- [x] hide Proposal
- [x] hide Flag
![image](https://user-images.githubusercontent.com/19403453/57286391-bb154380-70e7-11e9-9633-acb398d012df.png)

**Comment by cmngan** [comment]
no hide, change to under development text

**Comment by hkykit** [comment]
Dispute and honour
![image](https://user-images.githubusercontent.com/19403453/57302884-c0d24f80-710e-11e9-8917-bbadbf2630c4.png)

proposal
![image](https://user-images.githubusercontent.com/19403453/57302899-c6c83080-710e-11e9-8a82-541e98d99d96.png)

Dispute in nav
![image](https://user-images.githubusercontent.com/19403453/57302910-cdef3e80-710e-11e9-929e-99e17de5950a.png)
