### ISSUE TITLE
Terms of service

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#139]
1. create a html for terms of services 
2. Please host it in another link in IPFS for the doc
3. replacing the link in the following places:

in trade
![image](https://user-images.githubusercontent.com/19403453/57294258-a17cf780-70f9-11e9-8622-8ae6665b7acc.png)

in portfolio 
![image](https://user-images.githubusercontent.com/19403453/57294267-a772d880-70f9-11e9-86ae-edc4236e4be3.png)

**Comment by cmngan** [comment]
Using this file
[Terms of Service.pdf](https://github.com/smartupdev/smartup-dapp-ui/files/3152426/Terms.of.Service.pdf)
Url: https://ipfs.smartup.global/ipfs/QmWsxWygt8khjBkWwUoniLFPq5HU9nteJRxarPGUbWLJFV

**Comment by hkykit** [comment]
it works
https://ipfs.smartup.global/ipfs/QmWsxWygt8khjBkWwUoniLFPq5HU9nteJRxarPGUbWLJFV

wording changed to Terms of Service too
![image](https://user-images.githubusercontent.com/19403453/57304013-13ad0680-7111-11e9-9ebb-093d7c886a68.png)
