### ISSUE TITLE
Main Page Market description number of characters limitation 

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#14]
repo.
1. create market
2. input market description '1234'
3. move to Price Equation
4. move to Deposit and click on Create
5. Cannot create a market, 'Market description 2~30 characters' appeared

**Comment by hkykit** [comment]
Validation is done page by page now, so "Next" button is disabled when the requirement has not yet fulfilled.
when the requirement has not yet fulfilled, alert in red will be shown besides the name too
