### ISSUE TITLE
MP- 7D graph 描繪錯誤

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#147]
![image](https://user-images.githubusercontent.com/19403453/57369775-0cddcc80-71c1-11e9-9eaa-19be96269437.png)
![image](https://user-images.githubusercontent.com/19403453/57369818-23842380-71c1-11e9-8cda-acf46f09d204.png)

**Comment by ZhangZhen-SmartUp** [comment]
已修复

**Comment by hkykit** [comment]
fixed.
![image](https://user-images.githubusercontent.com/19403453/57750333-6d668f80-7714-11e9-8e78-38549576b698.png)
![image](https://user-images.githubusercontent.com/19403453/57750343-75263400-7714-11e9-8427-2878a2c85af1.png)


![image](https://user-images.githubusercontent.com/19403453/57750362-8a9b5e00-7714-11e9-84ce-52e441cdb385.png)

![image](https://user-images.githubusercontent.com/19403453/57750347-79eae800-7714-11e9-8274-4ada7f0075cf.png)

**Comment by hkykit** [comment]
Pick time at 0600, 1200, 1800, 2400
so the graph is reasonable

![image](https://user-images.githubusercontent.com/19403453/58066553-5e705900-7bbc-11e9-8a18-b4876bd1b368.png)
