### ISSUE TITLE
Trading - the recent transactions sorting & Last Price

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#151]
Daenerys & kittest sell idea  tokens at same time.

Problem 1: the recent transactions sorting
repo.

1. kittest sell instruction arrived back-end first, then Daenerys's
2. Daenerys's sell successfully first then kittest's
3. the recent transactions, sorted by the time that back-end received the sell instruction

expected
the recent transactions, should sort by the time on chain sell successfully.
   
Problem 2: Last Price should be 0.94 
![image](https://user-images.githubusercontent.com/49937934/57436069-87febb80-7271-11e9-9bd6-65c6ce8c2252.png)

**Comment by ZhangZhen-SmartUp** [comment]
用户在通过浏览器的metamask发出交易的时候，因为交易手续费的设置的不同，或者其他网络原因，导致交易完成的先后顺序不同，这个交易是在链上完成的，我们的程序没有办法控制。 当交易在链上完成后，我们的程序再按照链上的顺序抓取链上数据，在我们平台展示出来。
