### ISSUE TITLE
Create Mkt - cannot click 'Next' after I login

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#156]
repo.
1. Logged out
2. Create a Market, click on next
3. 'You had not logged in yet.' appeared (Correct)
4. Logged in
5. the next button has dimmed down, cannot click on it
![image](https://user-images.githubusercontent.com/49937934/57505054-81337f80-7329-11e9-9a16-5292fdb497d2.png)

**Comment by cmngan** [comment]
fixed

**Comment by karlischan** [comment]
fixed
