### ISSUE TITLE
Logout Metamask and click connect again, no response

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#162]
Logout Metamask and click connect again, no response

expected:
Logout Metamask and click connect again
Metamask popup for password to login Metamask

**Comment by cmngan** [comment]
Please check again =]

**Comment by karlischan** [comment]
![image](https://user-images.githubusercontent.com/49937934/58074795-ad2bec00-7bd8-11e9-800b-674f10925d0a.png)
fixed, a hint appeared asking for login in MetaMask.
