### ISSUE TITLE
Removed Metamask while logged in

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#165]
repo.
1. login metamask
2. remove the metamask fromChrome
3. no auto logout
4. go to trade
5. error occur

**Comment by cmngan** [comment]
I think we don't need to support that situation because that's not a normal user will do. 
Anyway, I tried to handle it. But not for all cases.

**Comment by karlischan** [comment]
![image](https://user-images.githubusercontent.com/49937934/58446470-6d628880-8133-11e9-878b-8696f86e132f.png)
handled
