### ISSUE TITLE
Translate to Chi

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#166]
1. Notifications_
![image](https://user-images.githubusercontent.com/49937934/58062912-cddf4c00-7bae-11e9-8aff-7288179fc85b.png)
Market Is Created
巿場已成功創建！
巿场已成功创建！

Used 2500 SmartUp created market “abc”
使用2500 SmartUp 創建巿場"abc"
使用2500 SmartUp创建巿场“abc”

Trade (Sell)/(Buy) Completed!
交易 (賣出)/(買入) 完成！
交易(卖出)/(买入)完成！

Sold/Buy 12314 token in "abc".
在"abc" 賣出/買入 12314巿場代幣
在"abc" 卖出/买入12314巿场代币

2. Trading Status
![image](https://user-images.githubusercontent.com/49937934/58062956-f0716500-7bae-11e9-90c4-eb530d73a7c9.png)
成功
失敗
處理中

成功
失败
处理中

3. Discussion 的紅字限制文字 (欠繁中)
![image](https://user-images.githubusercontent.com/49937934/58063203-ce2c1700-7baf-11e9-94ef-a290158e80be.png)
簡中: 帖子标题不能为空
繁中: 帖子標題不能為空

簡中: 帖子标题长度为3 - 350个字符
繁中: 帖子標題長度為3 - 350個字符

簡中: 回复内容不能为空
繁中: 回覆內容不能為空

簡中: 回复内容长度为2 - 300个字符
繁中: 回覆內容長度為2 - 300個字符

**Comment by karlischan** [comment]
回"覆"打錯字
![image](https://user-images.githubusercontent.com/49937934/58446342-fb8a3f00-8132-11e9-9756-e1809f505485.png)
![image](https://user-images.githubusercontent.com/49937934/58446377-1fe61b80-8133-11e9-87e8-13fa3020d723.png)

**Comment by karlischan** [comment]
![image](https://user-images.githubusercontent.com/49937934/58620637-283c8300-82fa-11e9-93c6-03e1572e2f42.png)
翻譯: 請先登入。

**Comment by karlischan** [comment]
![image](https://user-images.githubusercontent.com/49937934/58776008-08a7a200-85fb-11e9-9516-64a4ea001e19.png)
翻譯: 必需上載圖片

**Comment by ZhangZhen-SmartUp** [comment]
@cmngan  看已一下，有些可能是前端需要翻译的

**Comment by karlischan** [comment]
added
