### ISSUE TITLE
[FAQ] URL color

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#169]
The color of the URL in FAQ is too dark, hard to read.
![image](https://user-images.githubusercontent.com/49937934/58226617-040cff00-7d5a-11e9-90fb-50dea1f5b42c.png)

**Comment by cmngan** [comment]
fixed

**Comment by karlischan** [comment]
Fixed
![image](https://user-images.githubusercontent.com/49937934/58446084-ef51b200-8131-11e9-9c9d-bab205278c46.png)
