### ISSUE TITLE
Beta 上的交易在localhost上出現

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#177]
**Describe the bug/錯誤描述**
Beta 上的交易在localhost上出現

**To Reproduce/錯誤出現的步驟**
1. 在beta以account 3在market賣入ct 50000
HK countryside & ecosystem documentary
0x4B4aaae71a8e6327fB13feF2778f9B2c760b5d43

2. 在local host 中account 3自動賣入local host 的另一個market ct 50000
小明上廣州食大餐
0x4B4aaae71a8e6327fB13feF2778f9B2c760b5d43

3. 兩個market　address一樣會ct價格會一樣，交易會互相影響

**Comment by ZhangZhen-SmartUp** [comment]
是的，会出现这样的情况，因为他们的链上信息都写在ropsten网络里的，可以在不同的环境中使用不同的账户创建市场就可以避免这种情况。
因为我们的测试环境比价多，连接不同的网络，需要搭建不同的节点，会有服务器的成本

**Comment by karlischan** [comment]
正式時使用Main network 和只有一個backend 就沒有問題
