### ISSUE TITLE
PC market background color

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#194]
the bg color of the market icon photo should as dark as the other column
![image](https://user-images.githubusercontent.com/49937934/61111281-cdcb4080-a4bb-11e9-9f08-d081463c91ed.png)

**Comment by cmngan** [comment]
should be fixed

**Comment by karlischan** [comment]
OK 
![image](https://user-images.githubusercontent.com/49937934/64322901-012ad700-cff6-11e9-936a-f38addc3f647.png)
