### ISSUE TITLE
MP - Populous tag is not showing the markets according community members 

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#20]
Populous tag is not showing the markets according community members.
Community members means the users who own the CT.

**Comment by cmngan** [comment]
@Silcence Check the key

**Comment by Silcence** [comment]
key是正确的， @ZhangZhen-SmartUp 看一下

**Comment by hkykit** [comment]
@ZhangZhen-SmartUp 查後發還給 @Silcence

**Comment by ZhangZhen-SmartUp** [comment]
已经修复好， 但是历史的数据会有问题，可以创建一个新的market，数据会在新的market里是正常的

**Comment by karlischan** [comment]
RELATED TO #106
