### ISSUE TITLE
Main Page 'All' tab sort by Name is not work as expected

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#22]
![image](https://user-images.githubusercontent.com/49937934/56777186-ae007680-6802-11e9-9b39-acad08d02b8e.png)
![image](https://user-images.githubusercontent.com/49937934/56777199-c07ab000-6802-11e9-9539-53cd4b97e95c.png)

**Comment by hkykit** [comment]
![image](https://user-images.githubusercontent.com/19403453/56787827-495c1080-6830-11e9-9196-692d777ad4ba.png)
no sorrting for name

close if you noticed, thanks
