### ISSUE TITLE
MP - refine format of 24H change % 

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#25]
1. Main Page 24h change % is not as same as the 24H CHANGE% in Portfolio 
2. Main Page 24h change % should be in format
--> +18.34%, or -18.24% (with +/-, 2 decimal places )
![image](https://user-images.githubusercontent.com/19403453/56943233-1deb6580-6b51-11e9-9de1-74ca31e4a837.png)

3. Main Page 24h change % is too long and overlapped with the spot price

![image](https://user-images.githubusercontent.com/49937934/56794717-4cabc800-6841-11e9-8989-ef9cba5642a6.png)

**Comment by cmngan** [comment]
@ZhangZhen-SmartUp For 1, any idea?

**Comment by karlischan** [comment]
fixed
![image](https://user-images.githubusercontent.com/49937934/57116043-3774f300-6d85-11e9-85e6-d7fc8c272e23.png)
