### ISSUE TITLE
MP - search bar, no 'x' to close the search field

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#27]
![image](https://user-images.githubusercontent.com/49937934/56795972-381cff00-6844-11e9-81fb-9e17419b53b5.png)

![image](https://user-images.githubusercontent.com/49937934/56796063-5d117200-6844-11e9-964a-eb8f4cecfd39.png)

**Comment by cmngan** [comment]
I don't think the 'X' is needed. And there is not design for that. @hkykit
