### ISSUE TITLE
MP - 24 volume and Funding Cap have no standard rounding

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#28]
![image](https://user-images.githubusercontent.com/49937934/56798156-d612c880-6848-11e9-975d-a34380456ad3.png)
![image](https://user-images.githubusercontent.com/49937934/56798273-0bb7b180-6849-11e9-9480-b50e614de857.png)

**Comment by hkykit** [comment]
![image](https://user-images.githubusercontent.com/19403453/56892037-f80e8400-6ab0-11e9-86a1-9572a81f6404.png)

![image](https://user-images.githubusercontent.com/19403453/56892044-fe046500-6ab0-11e9-8e98-8163bb43b1c5.png)

**Comment by cmngan** [comment]
may be done?

**Comment by karlischan** [comment]
FIXED
