### ISSUE TITLE
Notification: unread notifications don't have a lighter color

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#29]
![image](https://user-images.githubusercontent.com/49937934/56801445-0447d680-6850-11e9-95f4-798b7e416796.png)
![image](https://user-images.githubusercontent.com/49937934/56801400-ebd7bc00-684f-11e9-9262-0e32602fb6d1.png)

**Comment by cmngan** [comment]
Change to use green dot now. @hkykit

**Comment by hkykit** [comment]
OK
