### ISSUE TITLE
Portfolio - Retrieve wrong number of ETH

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#3]
i have 4 in the wallet, it said 3.
repo:
1. Have 5 ETH in wallet
2. send out 1 ETH
3. transaction confirmed
4. No change in portfolio, still showing 5 ETH
5. Refresh browser, and it auto log out
6. re-connect, it shows 3 ETH

![image](https://user-images.githubusercontent.com/19403453/55791922-23c1ce00-5af2-11e9-9431-77373ba0c89e.png)
![image](https://user-images.githubusercontent.com/19403453/55791934-2ae8dc00-5af2-11e9-98b5-62973d0eeea1.png)

**Comment by cmngan** [comment]
try it again

**Comment by hkykit** [comment]
still the old until i refreshed.

**Comment by cmngan** [comment]
Fixed and plz check

**Comment by hkykit** [comment]
it is auto-refreshed
