### ISSUE TITLE
Trade - add one more status column in recent transaction

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#39]
only show completed and pending, no failed will be shown

**Comment by hkykit** [comment]
用以下狀態： 
Success
Pending

**Comment by cmngan** [comment]
@Silcence there is a function in util, i think in string.js

**Comment by Silcence** [comment]
Fixed

**Comment by hkykit** [comment]
updated
![image](https://user-images.githubusercontent.com/19403453/57222131-14bc3600-7034-11e9-9a36-d689588db2ab.png)
![image](https://user-images.githubusercontent.com/19403453/57222145-24d41580-7034-11e9-9ea2-caf216b92eee.png)
