### ISSUE TITLE
Create market - update max character from 20 to 40 in name

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#40]
from 20 max to 40 max please
![image](https://user-images.githubusercontent.com/19403453/56886005-8c241f80-6aa0-11e9-82d6-66d7a8bcd112.png)

**Comment by hkykit** [comment]
is 3-40
![image](https://user-images.githubusercontent.com/19403453/56943704-51c78a80-6b53-11e9-9f01-7c50776d0684.png)

**Comment by hkykit** [comment]
@ZhangZhen-SmartUp 
Update the backend validation from 3-30 to 3-40
![image](https://user-images.githubusercontent.com/19403453/57119688-b9254a80-6d9e-11e9-876d-d3c70e01d832.png)

**Comment by karlischan** [comment]
@ZhangZhen-SmartUp 
Update the backend, market description 1-150 characters
![image](https://user-images.githubusercontent.com/49937934/57126747-a3288180-6dc0-11e9-943e-a53f7e0eb138.png)

**Comment by ZhangZhen-SmartUp** [comment]
已经修好了

**Comment by hkykit** [comment]
fixed
