### ISSUE TITLE
MP - 討論的帖子數目比實際多了1

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#41]
![image](https://user-images.githubusercontent.com/49937934/56886129-d1485180-6aa0-11e9-95a2-1c8786d02773.png)

只有4個帖子
![image](https://user-images.githubusercontent.com/49937934/56886084-b970cd80-6aa0-11e9-8cef-f717a50f0cef.png)

**Comment by cmngan** [comment]
i think it is because of the data clean up issue. Please create a new market and see if the issue still exists. If yes, assign to @ZhangZhen-SmartUp
