### ISSUE TITLE
Create mkt - handle mkt logging in when market is creating

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#42]
**Current:**
1. i didnt log in
2. i fill in info to create a markter
3. click create
4. back and create button disabled, nothing changed in create market
5. Found there is a hidden pop up in metamask calling to login
6. Type in pw to login
7. Portfolio showed with collected market, nothing changed in create market
8. go to other tab and back to create market tab, back and create button enabled
9. Click create again
10. pop up box calling for signature

**Expected**
1. When i clicked "Create" without logging in 
--> either show metamask pop up if not yet login Metamask
--> or show alert calling user to log in

2. after logging in, the page SHOULD auto refresh to 
--> either enable the "Create" "Back" button
--> or pop up

**Comment by cmngan** [comment]
fixed

**Comment by hkykit** [comment]
Repro:
1. i didnt log in
2. i fill in info to create a markter
3. click create
4. now is
![image](https://user-images.githubusercontent.com/19403453/57119463-fc7eb980-6d9c-11e9-8e88-65a3c68ff636.png)
Back and Create button enabled, show proper alert
5. Found there is a hidden pop up in metamask calling to login
6. Type in pw to login
7. Portfolio showed with collected market, nothing changed in create market
8. Click create again
10. pop up box calling for connection.
11. Market created


**Both expected behaviour achieved**
When i clicked "Create" without logging in
--> either show metamask pop up if not yet login Metamask
--> or show alert calling user to log in

after logging in, the page SHOULD auto refresh to
--> either enable the "Create" "Back" button
--> or pop up
