### ISSUE TITLE
Create market - market icon 應是圓形

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#43]
不是正方形
![image](https://user-images.githubusercontent.com/19403453/56887329-e4105580-6aa3-11e9-91aa-9d5a66dd8149.png)

**Comment by hkykit** [comment]
NOT YET FIXED
![image](https://user-images.githubusercontent.com/19403453/56943687-39577000-6b53-11e9-973f-76b0223fe38c.png)

**Comment by Silcence** [comment]
fixed

**Comment by hkykit** [comment]
checked
![image](https://user-images.githubusercontent.com/19403453/56956403-a0d2e700-6b76-11e9-97dc-efb7c7a8c942.png)
