### ISSUE TITLE
Portfolio: market wallet & Bookmark cannot load more for more markets

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#44]
![image](https://user-images.githubusercontent.com/49937934/56889053-0dcb7b80-6aa8-11e9-99c4-4ca28cce3cb6.png)

![image](https://user-images.githubusercontent.com/49937934/56889277-88949680-6aa8-11e9-84d5-1e77f0ea7f24.png)

**Comment by karlischan** [comment]
Market wallet出現很多沒有買入market token 的markets

![image](https://user-images.githubusercontent.com/49937934/57057661-25d81080-6cdd-11e9-8462-3ca96a1faf26.png)

**Comment by cmngan** [comment]
#44

**Comment by cmngan** [comment]
fixed

**Comment by karlischan** [comment]
fixed
