### ISSUE TITLE
MP - default sort by last price, light up 'LAST PRICE' & upside arrow

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#45]
![image](https://user-images.githubusercontent.com/49937934/56889594-62bbc180-6aa9-11e9-9638-f4ee70c196d5.png)

**Comment by hkykit** [comment]
FIXED 
![image](https://user-images.githubusercontent.com/19403453/56943633-ff866980-6b52-11e9-8ee9-d06cae32c643.png)
