### ISSUE TITLE
Discussion : Uploaded a pic and the pic ratio is distorted

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#46]
![image](https://user-images.githubusercontent.com/49937934/56889759-e1b0fa00-6aa9-11e9-98ba-0273b9a968af.png)

**Comment by hkykit** [comment]
photo width greater than screens size: adapt by screen width
photo width less than screens size: actual size

Accept all height.

**Comment by karlischan** [comment]
fixed
![image](https://user-images.githubusercontent.com/49937934/57116020-072d5480-6d85-11e9-9ffa-a2a66abc0ddb.png)
