### ISSUE TITLE
Discussion : Click on the reply icon, a dislike generated

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#47]
Click this:
![image](https://user-images.githubusercontent.com/49937934/56889867-4a987200-6aaa-11e9-9039-81fe81709785.png)

Result:
![image](https://user-images.githubusercontent.com/49937934/56889902-613ec900-6aaa-11e9-8954-e98011f66f6d.png)

**Comment by cmngan** [comment]
我也是醉了
