### ISSUE TITLE
Discussion: latest post should be on top 

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#48]
![image](https://user-images.githubusercontent.com/49937934/56890808-1ecabb80-6aad-11e9-88d5-86ca461e986f.png)

**Comment by ZhangZhen-SmartUp** [comment]
已经修改好了

**Comment by karlischan** [comment]
great!
![image](https://user-images.githubusercontent.com/49937934/57195877-e5e98580-6f89-11e9-9116-32e14ee382c8.png)
