### ISSUE TITLE
Settings - length should be 6-15

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#50]
![image](https://user-images.githubusercontent.com/19403453/56938829-fa1b2600-6b36-11e9-8f98-f21ee507a7b6.png)

需求
![image](https://user-images.githubusercontent.com/19403453/56938841-056e5180-6b37-11e9-9923-fdfbfb17e8b8.png)

**Comment by Silcence** [comment]
Fixed

**Comment by hkykit** [comment]
@Silcence 沒做這塊
1. 按Submit, 彈出 "this action is irreversible.", 本來的Submit button也變了 左面Confirm ，右面Cancel
![image](https://user-images.githubusercontent.com/19403453/57209477-30f7ad00-700b-11e9-8e19-1070a3eb440b.png)

2. 再按Confirm才成功
3. 按Cancel 取消任何改變，變回Submit  button

如果按了Confirm 之前，又把名字改了，就還是顯示Confirm Cancel buttons 就好

**Comment by Silcence** [comment]
Fixed

**Comment by hkykit** [comment]
fixed
![image](https://user-images.githubusercontent.com/19403453/57221873-497bbd80-7033-11e9-9adf-d8b21b27e98e.png)

Please also fix:
1. Should hide the confirm and cancel button after user clicked Confirm
![image](https://user-images.githubusercontent.com/19403453/57221954-81830080-7033-11e9-96ec-6e291e340d25.png)

**Show Submit button if user clicked Cancel**

2. After user changed the username, should 
- hide the submit button
- update the sentence from "Capital sensitive, 6-15 characters." to " Username is confirmed and locked."

**Comment by hkykit** [comment]
Please also fix:
1. Should hide the confirm and cancel button after user clicked Confirm
![image](https://user-images.githubusercontent.com/19403453/57221954-81830080-7033-11e9-96ec-6e291e340d25.png)

**Show Submit button if user clicked Cancel**

2. After user changed the username, should 
- hide the submit button
- update the sentence from "Capital sensitive, 6-15 characters." to " Username is confirmed and locked."

**Comment by Silcence** [comment]
Fixed

**Comment by hkykit** [comment]
should prohibit user clicking Submit when the validation is failed
![image](https://user-images.githubusercontent.com/19403453/57749172-920c3880-770f-11e9-9df4-4893768e62c0.png)

**Comment by hkykit** [comment]
should prohibit user clicking Submit when the validation is failed

**Username:**
Current: can click Submit
Expected: 
Submit is disabled until username falls into 6-15 characters
![image](https://user-images.githubusercontent.com/19403453/57749172-920c3880-770f-11e9-9df4-4893768e62c0.png)


**Pictures**
Current: can click Submit
Expected: Submit is disabled until image is uploaded

**Comment by hkykit** [comment]
related to #163

**Comment by hkykit** [comment]
this is fixed.
