### ISSUE TITLE
Settings - Photo cant be uploaded now

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#51]
No action after clicking Submit button

**Comment by Silcence** [comment]
我这里是可以的

**Comment by hkykit** [comment]
no response after clicking Submit
![image](https://user-images.githubusercontent.com/19403453/56956356-7aad4700-6b76-11e9-8744-6ceed6be6798.png)

**Comment by Silcence** [comment]
Fixed

**Comment by hkykit** [comment]
- [ ] 1. able to upload the photo
- [ ] 2. Able to return to default icon by cancelling the existed photo
- [ ] 3. able to change photo by uploading
- [ ] 4. Able to drag and upload photo
- [ ] 5. able to change photo by drag drop

**Comment by hkykit** [comment]
#2 CAN DO BY THE FOLLOWING STEPS
1. cancel the existed photo
2. click submit
3. photo returns to original photo

# 5 will be settled in #127.
