### ISSUE TITLE
FAQ Page

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#52]
1. 二十條問題，只有問題，打開向下拉
2. 每打開一個，把本來打開的收起
3. 不用做分頁
4. 把每個的內文有以下三件 - title, 內文，圖片, 我稍後會再去更新文字

**Comment by hkykit** [comment]
把FAQ 的內文底加一點空間
把FAQ頁 放在左下角，FAQ icon 已經有

**Comment by hkykit** [comment]
![image](https://user-images.githubusercontent.com/19403453/57205569-1533dd00-6ff2-11e9-8d18-14d70fe5a645.png)

**Comment by Silcence** [comment]
fixed

**Comment by hkykit** [comment]
原型圖在這裹https://lanhuapp.com/web/#/item/project/board/detail?pid=2b6a7a64-33cb-4b4d-b06e-6ed33e47507c&project_id=2b6a7a64-33cb-4b4d-b06e-6ed33e47507c&image_id=805e2f1c-4c89-4490-afa9-52a16b2e26d7

FAQ 左邊要加空間，title 也要靠左

**Comment by hkykit** [comment]
done and reformatted
