### ISSUE TITLE
Redirection from smartup.global

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#55]
![image](https://user-images.githubusercontent.com/19403453/56939446-fc7f7f00-6b3a-11e9-8cc1-724b400d4355.png)
1. click "Start a project" -> 去跳轉頁 -> 去現在創建市場的頁面
2. click "Explore project" -> 去跳轉頁 -> 去現在主頁

**Comment by Silcence** [comment]
等待发布到线上

**Comment by hkykit** [comment]
done
