### ISSUE TITLE
MP - 24H Change should show as 2 decimal and with % (e.g. 18.39%)

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#56]
![image](https://user-images.githubusercontent.com/49937934/56940205-787bc600-6b3f-11e9-9eaf-621714d21bd8.png)

![image](https://user-images.githubusercontent.com/49937934/56940218-8df0f000-6b3f-11e9-81c0-ce7cb83cc81b.png)

**Comment by hkykit** [comment]
RELATED TO #25
