### ISSUE TITLE
Mkt - Update subscriber icon

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#59]
size of subscriber's icon and number should be same as post icon and number
![image](https://user-images.githubusercontent.com/19403453/56943109-9271d480-6b50-11e9-8cea-377a850f5253.png)

**Comment by Silcence** [comment]
需要UI重新切一下subscriber的Icon.

**Comment by cmngan** [comment]
The icon and number size is same. Should we enlarge it?

**Comment by hkykit** [comment]
done
![image](https://user-images.githubusercontent.com/19403453/57749335-2c6c7c00-7710-11e9-8e49-13a939f40b96.png)
