### ISSUE TITLE
Portfolio - use market name instead of market ID 

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#62]
use market name instead of market ID , max length = 9
![image](https://user-images.githubusercontent.com/19403453/56943387-d9ac9500-6b51-
11e9-9605-fbd3d3634020.png)

**Comment by cmngan** [comment]
@ZhangZhen-SmartUp Need to add market name to the api
/api/user/ct/account/in/market?pageNumb=2&pageSize=10

**Comment by ZhangZhen-SmartUp** [comment]
添加了
![image](https://user-images.githubusercontent.com/47549371/57192469-7eb8da80-6f63-11e9-9149-4ba79af63b81.png)

**Comment by cmngan** [comment]
fixed

**Comment by karlischan** [comment]
FIXED
