### ISSUE TITLE
MP - Last Price in MP is not as same as the price in trading page

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#63]
![image](https://user-images.githubusercontent.com/49937934/56943694-41afab00-6b53-11e9-9797-cf732576774c.png)

![image](https://user-images.githubusercontent.com/49937934/56943703-512ef400-6b53-11e9-8cae-5d9e00bd11ca.png)

**Comment by cmngan** [comment]
fixed.

**Comment by karlischan** [comment]
fixed
