### ISSUE TITLE
Login - didnt sign out

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#64]
1. login successfully
2. go to chrome://extensions, turn off metamask and turn on again
3. go back to the page, portfolio still show with data but metamask has been signed in
![image](https://user-images.githubusercontent.com/19403453/56945255-23e54480-6b59-11e9-9bcc-2091b9acee59.png)

**Comment by cmngan** [comment]
There is no good solution for detecting metamask enabled or not. 
And metamask won't return from the function call if toggling metamask disability. 
This case is not common and user should know how to do if they intend to do that.

**Comment by hkykit** [comment]
It is same as Augur, guess there is no good solution around at this moment.
