### ISSUE TITLE
Login - should auto logout when user clicked logout

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#65]
didnt successfully logout after i clicked logout
![image](https://user-images.githubusercontent.com/19403453/56945747-b89c7200-6b5a-11e9-96ca-3710de237066.png)

**Comment by cmngan** [comment]
fixed

**Comment by hkykit** [comment]
Augur will be auto log off after few second.

For SmartUp, click any MM related action, the page will be log out. But for non-MM action, it remains unchanged. 

Expected: Should auto log out like Augur

**Comment by hkykit** [comment]
fixed
