### ISSUE TITLE
Refine redirect page

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#66]
https://codepen.io/anon/pen/xeeoMR

1. 減少spacing between RIRECT NOTICE and subtitle in IPHONE X
![image](https://user-images.githubusercontent.com/19403453/56947394-ac66e380-6b5f-11e9-8b7a-dca0fc0b4f1a.png)

**Comment by Silcence** [comment]
fixed

**Comment by hkykit** [comment]
建好redirect page, 放到網上，放URL 在這裡，我再看看是不是有 要轉到最新ipfs平台

**Comment by hkykit** [comment]
- [ ] 1. 用相同的背景色可以嗎？
- [ ] 2. 要加這段文字
You are now leaving SmartUp.global and entering a website with no affiliation, support, or relationship to the Smart Up Incubator Limited.
Smart Up Incubator Limited does not endorse this website, its sponsor, or any policies, activities, products, or services offered on the site by any any advertiser or service provider on this site. Smart Up Incubator Limited cannot attest to the accuracy of the information provided by this link. You will be subject to the destination site's privacy policy when you follow the link. Services offered when following the link have no affiliation to Smart Up Incubator Limited, and Smart Up Incubator Limited makes no claims in relation to the following link.

- [ ] 3. 加文字時跟一下它的spacing https://codepen.io/anon/pen/xeeoMR

**Comment by Silcence** [comment]
背景色全局统一设置的，无法修改。文字和space已经添加。

**Comment by hkykit** [comment]
#2,3 已修改，設計師approved.
![image](https://user-images.githubusercontent.com/19403453/57749045-0abec500-770f-11e9-92e0-a44902a9f60f.png)
