### ISSUE TITLE
Login - Should keep refreshing Metamask status when it is newly install

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#67]
Repro:
1. Installed MM and then login successfully
2. turn off MM
3. Portfolio still didnt log out  (INCORRECT)
4. remove MM
5. back to platform, Portfolio still didnt log out (INCORRECT)
6. Refresh the page, show the below(CORRECT)
![image](https://user-images.githubusercontent.com/19403453/56947664-6fe7b780-6b60-11e9-8d72-ee6de34388c0.png)
7. re-Install MM
8. back to platform, Click Connect, nth change in platform, (INCORRECT)
9. MM pop up Get started, Import wallet again and succeed 
10. back to platform, Click Connect, Still nth change in platform (INCORRECT)

**Comment by cmngan** [comment]
it is not supported by metamask

**Comment by hkykit** [comment]
Augur couldn't check the status of MM too, the below is how Augur works:

1. Installed MM and then login successfully
2. turn off MM
3. Transaction record still didnt log out 
4. remove MM
5. back to Augur, Transaction record still didnt log out 
6. Refresh the page, logged out
8. re-Install MM
9. back to platform, Click Connect, nth change in platform
10. MM pop up Get started, Import wallet again and succeed
11. back to platform, Click Connect, Still nth change in platform

Until i refreshed the page, then MM requires me to connect with Augur again.

Same as how SmartUp works
