### ISSUE TITLE
Pop up portfolio when user clicked cancel on enabling metamask 

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#7]
repro:
1. Click Connect
2. metamask is launched
3. user click Cancel
4. the portfolio page pop up with data in less than one second then disappear
*can refresh the page and have same experience again

**Comment by cmngan** [comment]
try again

**Comment by hkykit** [comment]
the problem below doesnt appear anymore
the portfolio page pop up with data in less than one second then disappear
*can refresh the page and have same experience again
