### ISSUE TITLE
Login - cant login after changing account

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#70]
1. login account A
2. Change account from A to B,  MM auto logout (CORRECT)
3. Pop MM, requesting to sign signature
4. Click Sign
5. Portfolio with data shown and then immediately disappeared.
6. then show above
![image](https://user-images.githubusercontent.com/19403453/56952282-90b60a00-6b6c-11e9-9af8-7131ec28c366.png)

7. Open metamask, it has data and account changed to B
![image](https://user-images.githubusercontent.com/19403453/56952304-9e6b8f80-6b6c-11e9-846e-5289131757d6.png)
8. Click connect again
9. Requesting sign again
10, Click sign and then porfolio is successfully connected

**Comment by cmngan** [comment]
fixed

**Comment by hkykit** [comment]
can login now
