### ISSUE TITLE
Notification - should pop up message when im in the notification tab

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#73]
I stayed in notification tab, and create market at the same time
When i created a market successfully,

Current: green light turn on, message doesnt show when i received a notification
 ![image](https://user-images.githubusercontent.com/19403453/57054575-ed7a0780-6cc7-11e9-9cc4-bd8fb971745c.png)
Expect: green light turn on, message pop up when i received a notification

**Comment by hkykit** [comment]
didnt change

**Comment by cmngan** [comment]
Can't reproduce

**Comment by hkykit** [comment]
auto refresh and show msg now
