### ISSUE TITLE
Notification - Update message content

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#74]
- [ ] @ZhangZhen-SmartUp Please update content

**Create Market**
_Success_
Title: Market Is Created!
Content: Used 2500 SmartUp created market “{MarketName}”

_Fail_
Title: Market Is Not Created!
Content: Unable to create market “{MarketName}”

**Transaction**
Buy - success:
Title: Trade (Buy) Completed! 
Content: Bought {#ofToken} token in {MarketName}.

Buy - fail:
Title: Trade (Buy) Failed 
Content: Unable to buy {#ofToken} token in {MarketName}.

Sell - success:
Title: Trade (Sell) Completed! 
Content: Sold {#ofToken} token in {MarketName}.

Sell - fail:
Title: Trade (Sell) Failed! 
Content: Unable to sell {#ofToken} token in {MarketName}.

**Comment by cmngan** [comment]
BE required.

**Comment by ZhangZhen-SmartUp** [comment]
已经修改好了

**Comment by hkykit** [comment]
updated 
![image](https://user-images.githubusercontent.com/19403453/57221396-af674580-7031-11e9-93f6-97cf18075e75.png)

![image](https://user-images.githubusercontent.com/19403453/57221409-b726ea00-7031-11e9-969c-258d1b485dfd.png)
![image](https://user-images.githubusercontent.com/19403453/57221417-c27a1580-7031-11e9-9fb5-6330e8bf0f3a.png)

![image](https://user-images.githubusercontent.com/19403453/57221431-cf970480-7031-11e9-8018-1b09aaf12052.png)
