### ISSUE TITLE
Discussion - Created post, older posts are hidden, post number & redirection problem

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#77]
Problem 1.
repo.
1.  create a new post
2. created successfully and redirect to this page 
![image](https://user-images.githubusercontent.com/49937934/57058631-8c602d00-6ce3-11e9-8794-fac7d31a5933.png)
3. other older post disappeared
4. refresh the page, the newer posts disappeared
![image](https://user-images.githubusercontent.com/49937934/57058700-e3660200-6ce3-11e9-883c-9400f1bb0088.png)

Problem 2.
number of post is not correct
![image](https://user-images.githubusercontent.com/49937934/57074988-08746800-6d18-11e9-9ef9-49b5b364c6fa.png)

Problem 3.
click on and redirect to discussion
![image](https://user-images.githubusercontent.com/49937934/57123452-7c644e00-6db4-11e9-8a94-331143378fe5.png)

**Comment by karlischan** [comment]
number of post is not correct
![image](https://user-images.githubusercontent.com/49937934/57074988-08746800-6d18-11e9-9ef9-49b5b364c6fa.png)

**Comment by cmngan** [comment]
Problem is probably because of the data cleaning issue. Should be ok in new market.

**Comment by cmngan** [comment]
Fixed

**Comment by karlischan** [comment]
The search record keep existing when i visit another Market's Discussion
repo.
1. search 小明 in太空market
![image](https://user-images.githubusercontent.com/49937934/57138260-ca914580-6de4-11e9-8266-fed6b857f6b9.png)
2. go to another Market's Discussion
3. the record is still here:
![image](https://user-images.githubusercontent.com/49937934/57138333-fc0a1100-6de4-11e9-86bb-d45bf10a99cf.png)

**Comment by karlischan** [comment]
FIXED
