### ISSUE TITLE
Create mkt when metamask have no ETH, the error statement is hard to understand

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#78]
![image](https://user-images.githubusercontent.com/49937934/57060163-00520380-6ceb-11e9-8158-fc6c340a7895.png)

**Comment by karlischan** [comment]
repo.
1. create mkt page, step 3 click on 'create'
2. Reject to confirm in metamask
3. error statement appeared and the  error statement is hard to understand too
![image](https://user-images.githubusercontent.com/49937934/57060986-eebe2b00-6ced-11e9-94d8-ae66ab894d87.png)

**Comment by hkykit** [comment]
how to rerproduce your error?

i can only receive this

Node error: {"code":-32603,"message":"Error: MetaMask Tx Signature: User denied transaction signature."}

**Comment by hkykit** [comment]
@karlischan

**Comment by karlischan** [comment]
Change metamask to other test network or main network
@hkykit

**Comment by karlischan** [comment]
> repo.
> 
> 1. create mkt page, step 3 click on 'create'
> 2. Reject to confirm in metamask
> 3. error statement appeared and the  error statement is hard to understand too
>    ![image](https://user-images.githubusercontent.com/49937934/57060986-eebe2b00-6ced-11e9-94d8-ae66ab894d87.png)

maybe the error statement like this:
'Please sign in MetaMask to proceed.'

**Comment by hkykit** [comment]
the error is initiated by user, they shall know what happened, so using backend error should be the most clear message and precise.
