### ISSUE TITLE
Signature still show up even i clicked cancel when enabling metamask

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#8]
repro
1. 用戶之前有登入過 ( connect 過）
2. 重新yarn start, re-build
3. portal asking for Connect again
4. Click cancel
5. go to the page, it shows signature pop up and asking for signature

**Comment by cmngan** [comment]
try try

**Comment by hkykit** [comment]
it doesnt show signature pop up and asking for signature, instead, the sign in request stuck in metamask
![image](https://user-images.githubusercontent.com/19403453/56944984-0c598c00-6b58-11e9-9030-bc4d7ea33e9e.png)

and showed an instruction "Please check metamask" to notify user now, 
![image](https://user-images.githubusercontent.com/19403453/56945012-1bd8d500-6b58-11e9-81d0-268067a43db3.png)
