### ISSUE TITLE
Discussion - validation for create post

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#84]
**1. Update error mesgae** 
Error message:  "Title must be 3-350 characters."

**2. Update length**
_Title: 3-350 length
Text: 0-unlimited_

**3. Please follow requirement:**
e.g. Text is optional field
Requirement:
![image](https://user-images.githubusercontent.com/19403453/57068121-62b6fe00-6d03-11e9-99f0-36179e8bd170.png)

![image](https://user-images.githubusercontent.com/19403453/57066136-fdacd980-6cfd-11e9-9c81-a971bb54d85e.png)

**Comment by ZhangZhen-SmartUp** [comment]
@hkykit  Post text can not be unlimited,  it is dangerous. I will set max size is 100000, Is ok?

**Comment by ZhangZhen-SmartUp** [comment]
已经修好了

**Comment by Silcence** [comment]
Fixed

**Comment by karlischan** [comment]
When post content more than around 7500 characters, 'Failed to fetch' appear.
is that the max for 7500?

![image](https://user-images.githubusercontent.com/49937934/57208679-b1b4aa00-7007-11e9-8ab7-2007e40e187c.png)

**Comment by cmngan** [comment]
@karlischan Test it again

**Comment by karlischan** [comment]
OK, able to input and summit 100k characters
