### ISSUE TITLE
Notification - when reading unread mag, ReadAll button keep lighting up

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#86]
repo.

1. sell ct successfully
2. new notification come out
3. click on unread msg button
4. readall button should be dim down, but it still lighted up 
![image](https://user-images.githubusercontent.com/49937934/57067171-cdb30580-6d00-11e9-935f-9ee1939ef743.png)

**Comment by cmngan** [comment]
Maybe we should the design?

**Comment by karlischan** [comment]
click to readall is ok
