### ISSUE TITLE
Create Mkt & Discussion - using emoji causes 'system error'

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#87]
Create Market:
![image](https://user-images.githubusercontent.com/49937934/57067397-79f4ec00-6d01-11e9-8ce6-f44e94f1bcfe.png)
![image](https://user-images.githubusercontent.com/49937934/57067435-909b4300-6d01-11e9-815e-aeaaa5ef42b0.png)

Discussion new post
![image](https://user-images.githubusercontent.com/49937934/57067470-b294c580-6d01-11e9-8720-4ed4209b6db3.png)

Discussion REPLY
![image](https://user-images.githubusercontent.com/49937934/57067498-ca6c4980-6d01-11e9-9bbe-8867fab53e13.png)

**Comment by ZhangZhen-SmartUp** [comment]
已修复

**Comment by karlischan** [comment]
AMAZING!! USERNAME WORKS TOO!
![image](https://user-images.githubusercontent.com/49937934/57216086-66a79080-7021-11e9-8372-679b43beb0e2.png)
