### ISSUE TITLE
Discussion click on Share Button

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#90]
Should be able to copy the link of that post
![image](https://user-images.githubusercontent.com/49937934/57074445-74ee6780-6d16-11e9-9ce4-e4b33684258a.png)

**Comment by cmngan** [comment]
Related to #140

**Comment by karlischan** [comment]
Not working in IPFS.
copied and notification come out and appeared 'link copied'
but cannot paste out the link, seem no link be copied.

**Comment by hkykit** [comment]
![image](https://user-images.githubusercontent.com/19403453/57750022-13b19580-7713-11e9-82a1-bfc5148aac23.png)

https://ipfs.smartup.global/ipfs/QmXR4x6snQ9EME6SNLNMcGmTje4sYzMeJb7xRHTHB1Jiqi/#/market/discussion/details?postId=15568976151056384&id=3ske3ab4a9s

![image](https://user-images.githubusercontent.com/19403453/57750004-05637980-7713-11e9-8991-9b535c1bbb49.png)

https://ipfs.smartup.global/ipfs/QmXR4x6snQ9EME6SNLNMcGmTje4sYzMeJb7xRHTHB1Jiqi/#/market/discussion/details?postId=15568976151056384&id=3ske3ab4a9s

**Comment by hkykit** [comment]
both worked now
