### ISSUE TITLE
Trade - default  view in a Newly created market

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#93]
**SPOT DATA**
Current
![image](https://user-images.githubusercontent.com/19403453/57076216-b0d7fb80-6d1b-11e9-8b07-81d571bce859.png)

Expect
Show "-" when no spot data
![image](https://user-images.githubusercontent.com/19403453/57076347-06aca380-6d1c-11e9-9de2-0683e4bbdb03.png)

**RECENT TRANSACTION**

- [x] No "More" when no transaction
![image](https://user-images.githubusercontent.com/19403453/57076580-90f50780-6d1c-11e9-9ec8-c91ba15d0d27.png)

- [x] Show More until there are 21 transaction

**Comment by cmngan** [comment]
@ZhangZhen-SmartUp If the market is new created, please use null for the data inside `data`.
Request URL: http://39.105.101.248:86/api/market/one/by/id?marketId=33lozhiark0
![image](https://user-images.githubusercontent.com/20035088/57134226-083ba180-6dd8-11e9-8657-e107fe81f007.png)

**Comment by ZhangZhen-SmartUp** [comment]
@cmngan  market data 中的数据已处理 ， high low 是取k线的，如果找不到，请设置为"-"

**Comment by hkykit** [comment]
checked
top: brand new mkt
bottom: new mkt less than 24H
![image](https://user-images.githubusercontent.com/19403453/57206237-deac9100-6ff6-11e9-9791-b3f228b1bdc6.png)

checked the spot data
![image](https://user-images.githubusercontent.com/19403453/57206246-f4ba5180-6ff6-11e9-9711-3f89859a1740.png)


checked, only show Load more when 20 tx
![image](https://user-images.githubusercontent.com/19403453/57206255-0c91d580-6ff7-11e9-94bb-cf6b59467b26.png)
