### ISSUE TITLE
Trade - K 綫圖 （IMPORTANT）

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#94]
- [x] 1. price 的陰陽蠋跟funding pool 共用一樣y axis，道致上下bar 重疊問題
- [x] 2. 沒有了左上角的數據點 六個數據
- [x] 3. 右面： 24H Volume 應該SUT 結算，跟main page 一樣
新建市場第一筆交易後，應有24H volume, high ,low, 第一條bar
![image](https://user-images.githubusercontent.com/19403453/57299578-81eccb80-7107-11e9-81d9-d8a2147adb31.png)

- [x] 4. 舊mkt 會有即時時間點的bar, 但新mkt 即至少要等一小時才有一條bar，應該是第一個交易後就有第一條bar 
![image](https://user-images.githubusercontent.com/19403453/57299578-81eccb80-7107-11e9-81d9-d8a2147adb31.png)

- [x] 5. 不知為何，這裹拿了同一樣數字做high low, 但我之前有㑯格更低的
Current: 
![image](https://user-images.githubusercontent.com/19403453/57137803-7f2a6780-6de3-11e9-833c-782e3bc7dd53.png)
![image](https://user-images.githubusercontent.com/19403453/57137811-85204880-6de3-11e9-80be-003f0866d420.png)

Expect
![image](https://user-images.githubusercontent.com/19403453/57077357-702db180-6d1e-11e9-8fbc-b96d4d9b9b0e.png)

- [x] 6. 新開市場的第一條bar時間跟日期重疊，可改？ @Silcence 
![image](https://user-images.githubusercontent.com/19403453/57138610-b1d55f80-6de5-11e9-923a-5053813ce366.png)

- [x] 7. 上一小時最後價是 0.92 , 現在的最後價是.27, 8pm bar 應是紅色吧？對不"？
![image](https://user-images.githubusercontent.com/19403453/57138678-e517ee80-6de5-11e9-9365-ba885838c6b2.png)

- [x] 8. K 綫圖紅綠色對調了吧？
- [x] 9. 右邊的Number of CT 應該取所有buy 交易的總CT量
![image](https://user-images.githubusercontent.com/19403453/57225550-4981ba80-703f-11e9-89a0-cf4bae784738.png)
- [x] 10. 右邊的24H volume 錯 @Silcence 
今天是 May 6，最後交易在 May3，24H volume 理應是 0
![image](https://user-images.githubusercontent.com/19403453/57225928-49ce8580-7040-11e9-81f8-7b8be90abae4.png)
- [x] 11. 1-day 沒了線條 @Silcence 
![image](https://user-images.githubusercontent.com/19403453/57271479-3106b400-70c2-11e9-8555-d31fdbfbc19b.png)
- [x] 12. 24H CHANGE high low 錯了，high 應是 0.87? @ZhangZhen-SmartUp 
![image](https://user-images.githubusercontent.com/19403453/57271536-6a3f2400-70c2-11e9-8f6f-a58a599677c7.png)
- [x] 13. Add spacing at the top , e.g. highest price = 0.9, 上面加多一格空間，令六個數据與K綫不要重疊 @Silcence 
![image](https://user-images.githubusercontent.com/19403453/57272306-c192c380-70c5-11e9-8503-44f17e2f51c4.png)
- [x] 14. 沒有mouse over 時，那六個數據的 0.38 是什樣來？ @ZhangZhen-SmartUp 
下面 七點八點也有數据，七點應該有 bar?
![image](https://user-images.githubusercontent.com/19403453/57272477-79c06c00-70c6-11e9-99dc-0ae0a88d2329.png)

**Comment by Silcence** [comment]
3、4、8 fixed

**Comment by Silcence** [comment]
high and low fixed.

**Comment by Silcence** [comment]
add default tooltip

**Comment by hkykit** [comment]
- [ ] 9. 右邊的Number of CT 應該取所有buy 交易的總CT量


![image](https://user-images.githubusercontent.com/19403453/57225550-4981ba80-703f-11e9-89a0-cf4bae784738.png)

**Comment by hkykit** [comment]
- [ ] 10. 右邊的24H volume 錯
今天是 May 6，最後交易在 May3，24H volume 理應是 0
![image](https://user-images.githubusercontent.com/19403453/57225928-49ce8580-7040-11e9-81f8-7b8be90abae4.png)

**Comment by Silcence** [comment]
@ZhangZhen-SmartUp 数据问题需要你看一下

**Comment by hkykit** [comment]
- [ ] 11. 1-day 沒了線條

![image](https://user-images.githubusercontent.com/19403453/57271479-3106b400-70c2-11e9-8555-d31fdbfbc19b.png)

**Comment by hkykit** [comment]
- [ ] 12. 24H CHANGE high low 錯了，high 應是 0.87?
![image](https://user-images.githubusercontent.com/19403453/57271536-6a3f2400-70c2-11e9-8f6f-a58a599677c7.png)

**Comment by hkykit** [comment]
- [ ] 13. Add spacing at the top , e.g. highest price = 0.9, 上面加多一格空間，令六個數据與K綫不要重疊
![image](https://user-images.githubusercontent.com/19403453/57272306-c192c380-70c5-11e9-8503-44f17e2f51c4.png)

**Comment by hkykit** [comment]
- [ ] 14. 沒有mouse over 時，那六個數據的 0.38 是什樣來？
下面 七點八點也有數据，七點應該有 bar?

![image](https://user-images.githubusercontent.com/19403453/57272477-79c06c00-70c6-11e9-99dc-0ae0a88d2329.png)

**Comment by Silcence** [comment]
10 and 13 has fixed.

**Comment by hkykit** [comment]
#10 fixed
![image](https://user-images.githubusercontent.com/19403453/57302492-dd21bc80-710d-11e9-8b1a-4ac4d6418ce4.png)

**Comment by hkykit** [comment]
#13 加了上面，沒加下面？ @Silcence 
![image](https://user-images.githubusercontent.com/19403453/57302530-004c6c00-710e-11e9-8ce7-dbda9b4b79d9.png)

**Comment by hkykit** [comment]
3-6, 11-14 沒有fix 
@Silcence @ZhangZhen-SmartUp

**Comment by Silcence** [comment]
#13 下面也处理了，上面是最大值*1.1， 下面是最小值/1.2，但是最小只能是0，所以看着效果不明显。

**Comment by Silcence** [comment]
#11 Fixed

**Comment by ZhangZhen-SmartUp** [comment]
12 已修复，修复数据时，产生了一些重复的通知，请忽略
14 已修复，但是数据没有修复

**Comment by hkykit** [comment]
#3,4 fixed
![image](https://user-images.githubusercontent.com/19403453/57356987-5ec42980-71a4-11e9-99f5-32c036307e0b.png)

#6 fixed, 把價格的最低價 設為 最低價/2
![image](https://user-images.githubusercontent.com/19403453/57357320-3be64500-71a5-11e9-884e-e9dfd1164ad9.png)

**Comment by hkykit** [comment]
#13 fixed
