### ISSUE TITLE
Trade - not able to sell all CT (IMPORTANT)

### ISSUE THREAD

**Issue by hkykit** [smartupdev/smartup-dapp-ui#98]
not able to sell all 810400
![image](https://user-images.githubusercontent.com/19403453/57079213-7e7dcc80-6d22-11e9-9b0c-6a2e9cb01564.png)

but able to sell 810399
![image](https://user-images.githubusercontent.com/19403453/57079299-a10fe580-6d22-11e9-83c6-b6f68d5ede54.png)

After all, leave 1 in wallet
![image](https://user-images.githubusercontent.com/19403453/57079427-e46a5400-6d22-11e9-9ff6-f357ad91c9e2.png)

**Comment by hkykit** [comment]
Sometimes can do sometimes cant, please check what happen.

**Comment by ZhangZhen-SmartUp** [comment]
@hkykit  please give me user address

**Comment by hkykit** [comment]
0x4c7D0106A5cff26519c0BEF46b38FA6aA06f53dA

**Comment by zhengfengyi** [comment]
@hkykit  这个问题无法复现，我试了几笔同样的交易没问题，之后如果有问题出现，麻烦告诉我

**Comment by hkykit** [comment]
再出現了
![image](https://user-images.githubusercontent.com/19403453/57220132-c2c3e200-702c-11e9-
8346-e74d1d32901a.png)

**Data**
0xe4849b320000000000000000000000000000000000000000000152d15dcdc81fca980000
![image](https://user-images.githubusercontent.com/19403453/57220146-cc4d4a00-702c-11e9-8961-70bd13cef966.png)

**my wallet**
0x4c7D0106A5cff26519c0BEF46b38FA6aA06f53dA

**contract address**
0x5715b7f28E50F48B2087fccB660faE8c8F3d9fBB
**mkt id**
3dnelbj7dog

**Comment by hkykit** [comment]
@zhengfengyi  fixed the contract

**Comment by hkykit** [comment]
Wind fixed the contract, letting the last one to take all remaining SUT (even it is smaller than he should have)
