### ISSUE TITLE
Discussion & PC - should use the username instead of address 

### ISSUE THREAD

**Issue by karlischan** [smartupdev/smartup-dapp-ui#99]
![image](https://user-images.githubusercontent.com/49937934/57079616-4b880880-6d23-11e9-8d7f-c4e51df6b48c.png)

**Comment by karlischan** [comment]
the photo should be shown too
![image](https://user-images.githubusercontent.com/49937934/57079706-81c58800-6d23-11e9-8646-8c8bd458fb71.png)

**Comment by karlischan** [comment]
So as Personal Centre
![image](https://user-images.githubusercontent.com/49937934/57118534-85debd80-6d96-11e9-8a77-25dedb637906.png)

**Comment by Silcence** [comment]
Fixed

**Comment by karlischan** [comment]
fixed
